apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: nginx:1.24.0
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: backendservice
spec:
  selector:
    app: backend-app
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
