apiVersion: apps/v1
kind: Deployment
metadata:
  name: initnginxdep
  annotations:
    kubernetes.io/change-cause: "nginx:1.29-alpine with init container"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: initnginxdep
  template:
    metadata:
      labels:
        app: initnginxdep
    spec:
      containers:
      - name: initnginxdep
        image: nginx:1.29-alpine
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
          - containerPort: 80
        envFrom:
        - configMapRef:
            name: myapp1
      initContainers:
      - name: create-index-file
        image: ubuntu
        command: ["sh", "-c", "echo '<!DOCTYPE html><html><body><h1>Welcome to my app24! Created by Init Container.</h1></body></html>' > /usr/share/nginx/html/index.html"]
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        persistentVolumeClaim:
          claimName: zapp-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: initnginxdep-svc
spec:
  selector:
    app: initnginxdep
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80

---

apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
  namespace: default
type: Opaque
data:
  azurestorageaccountname: dGVycmFzYWRldmFzdG9yYWdl
  azurestorageaccountkey: c29tZS1iYXNlNjQtZW5jb2RlZC1rZXk=
