apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  backoffLimit: 4
  completions: 5
  parallelism: 2
  activeDeadlineSeconds: 60
  template:
    spec:
      containers:
      - name: myjobcont 
        image: ubuntu
        command: ["is", "Hello I am successful"]
        imagePullPolicy: IfNotPresent
      #restartPolicy: OnFailure
      restartPolicy: Never
