apiVersion: storage.k8s.io/v1 
kind: StorageClass
metadata: 
 name: managed-standard-ssd 
parameters: 
 cachingmode: ReadOnly 
 kind: Managed 
storageaccounttype: StandardSSD_LRS 
provisioner: kubernetes.io/azure-disk


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-standard-ssd

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: webcontent
          mountPath: "/usr/share/nginx/html/web-app"


