apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: mynginx 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: mynginx 
  template: 
    metadata: 
      labels: 
        app: mynginx 
    spec: 
      containers: 
      - image: nginx 
        name: mynginx

--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: mynginx-cip 
spec: 
  ports: 
  - port: 8090 
    protocol: TCP 
    targetPort: 80 
  selector: 
    app: mynginx 


---

apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: "LoadBalancer"
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  labels:
    name: myingress
spec:
  rules:
  - host: <Host>
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: <Service>
            port: 
              number: <Port>

