apiVersion: v1
kind: Pod
metadata:
  name: myapp-nginx01
  labels:
    name: myapp-nginx01
spec:
  containers:
  - name: consumer-cont
    image: nginx:1.14.2
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name: myemptydir
      mountPath: /usr/share/nginx/html
      readOnly: true
  - name: producer-cont
    image: nginx:1.14.2
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
    volumeMounts:
    - name: myemptydir
      mountPath: /usr/html
  volumes:
  - name: myemptydir
    emptyDir: {}


...
apiVersion: v1
kind: Pod
metadata:
  name: myapp-nginx01
  labels:
    name: myapp-nginx01
spec:
  containers:
  - name: consumer-cont
    image: nginx:1.14.2
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name: myemptydir
      mountPath: /usr/share/nginx/html
      readOnly: true
  - name: producer-cont
    image: nginx:1.14.2
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
    volumeMounts:
    - name: myemptydir
      mountPath: /usr/html
  volumes:
    persistentVolumeClaim:
      claimName: mypvc
 