apiVersion: v1
kind: Pod
metadata:
  name: myapp82
  labels:
    name: myapp82
spec:
  containers:
  - name: myapp82
    image: nginx:1.14.2
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
    - mountPath: /con-data
      name: my_hostpathvol
  volumes:
  - name: my_hostpathvol
    hostPath:
      path: /data
      type: DirectoryOrCreate
    


...

apiVersion: v1
kind: Pod
metadata:
  name: myapp82
  labels:
    name: myapp82
spec:
  containers:
  - name: myapp82
    image: nginx:1.14.2
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
    - mountPath: /con-data
      name: my_hostpathvol
  volumes:
  - name: my_hostpathvol
    # hostPath:
    #   path: /data
    #   type: DirectoryOrCreate
    configmap:
      name: myconfigmap
      items:
      - key: name
    
...

