apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-premium
  azureDisk:
    kind: Managed
    diskName: zapp-disk
    diskURI: /subscriptions/f4cb86cb-67d4-472d-ae51-beb5564e9c7d/resourcegroups/k8szappdisk/providers/Microsoft.Compute/disks/zapp-disk

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  # is there qa namespace for PVC
  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed-premium


---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-premium
provisioner: disk.csi.azure.com
parameters:
  kind: Managed
  storageaccounttype: Premium_LRS
  cachingmode: ReadOnly