apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
   matchExpressions:
     - key: app 
       operator: In
       values:
       - myapp
       - demoapp
  #  matchLabels:
  #   app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: nginx:1.21.0
          ports:
            - containerPort: 80
