apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: ClusterIP
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-nodeport
spec:
 type: NodePort
 selector:
   app: myapp
 ports:
   - protocol: TCP
     nodePort: 30001
     port: 80
     targetPort : 80
