apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: myapp
        image: nginx:1.25.0
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 80


---
