apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  annotations:
    kubernetes.io/change-cause: {{ index .Values.annotations "kubernetes.io.change-cause" | quote }}
spec:
  strategy:
    type: Recreate
  replicas: {{.Values.global.replicaCount}}
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: myapp
        image: {{.Values.global.image.repository}}:{{.Values.global.image.tag}}
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-{{ .Chart.Name }}
              key: location
        - name: APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-{{ .Chart.Name }}
              key: name
        - name: APP_LOCATION
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-{{ .Chart.Name }}
              key: location
        - name: APP_GROUP
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-{{ .Chart.Name }}
              key: group
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: {{ .Release.Name }}-apollo-html
         
            
